import { useEffect, useState } from "react";
import axios from "axios";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable"
import Header from "../components/Header";
import Cookies from "js-cookie";

const DentistDashboard = () => {
  const [scans, setScans] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const token = Cookies.get("token");

  useEffect(() => {
    const fetchScans = async () => {
      try {
        const response = await axios.get("https://dentistscan-app.onrender.com/api/scans", {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });

        setScans(response.data);
        console.log(response.data)
        setLoading(false);

      } catch (err) {
        if (err.response?.status === 403) {
          Cookies.remove("token");
          Cookies.remove("role");
        } else {
          setError(err.response?.data?.error || "Failed to fetch scans");
        }
        setLoading(false);
      }
    };

    fetchScans();
  }, [token,]);

  
const downloadPDF = (scan) => {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(18);
  doc.setTextColor(40, 60, 100);
  doc.text("OralVis Healthcare", 20, 20);

  doc.setFontSize(14);
  doc.setTextColor(60, 60, 60);
  doc.text("Patient Scan Report", 20, 30);

  // Table
  autoTable(doc, {
    startY: 40,
    head: [["Field", "Details"]],
    body: [
      ["Patient Name", scan.patientName],
      ["Patient ID", scan.patientId],
      ["Scan Type", scan.scanType],
      ["Region", scan.region],
      [
        "Upload Date",
        scan.uploadDate ? new Date(scan.uploadDate).toLocaleString() : "N/A",
      ],
    ],
    theme: "striped",
    headStyles: {
      fillColor: [66, 135, 245],
      textColor: 255,
      fontStyle: "bold",
    },
    bodyStyles: {
      textColor: 50,
    },
    styles: {
      fontSize: 12,
    },
  });

  // Add scan image
  const img = new Image();
  img.src = scan.imageUrl;
  img.crossOrigin = "anonymous";
  img.onload = function () {
    const finalY = doc.lastAutoTable.finalY + 10; // position after table
    doc.text("Scan Image:", 20, finalY + 10);
    doc.addImage(img, "JPEG", 20, finalY + 20, 160, 100);

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by OralVis Healthcare System", 20, 290);
    doc.save(`${scan.patientName}_scan.pdf`);
    alert("Pdf Downloaded. Please check your downloads")
  };
};
  if (loading)
    return (
      <div className="text-center mt-20 text-gray-600 text-lg font-medium">
        Loading scans...
      </div>
    );

  if (error)
    return (
      <div className="text-center mt-20 text-red-500 font-semibold">{error}</div>
    );

  if (scans.length === 0)
    return (
      <div className="text-center mt-20 text-gray-600 font-medium">
        No scans available yet.
      </div>
    );

  return (
    <>
      <Header />
      <div className="p-6 bg-gray-50 min-h-screen">
        <h1 className="text-3xl font-extrabold mb-6 text-gray-800">
          Dentist Dashboard
        </h1>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {scans.map((scan) => (
            <div
              key={scan.id}
              className="bg-white border border-gray-200 rounded-2xl shadow-lg p-5 flex flex-col justify-between transition transform hover:scale-105"
            >
              <img
                src={scan.imageUrl}
                alt={scan.patientName}
                className="w-full h-52 object-cover rounded-xl mb-4 shadow-sm"
              />
              <div className="mb-3 text-gray-700 space-y-1">
                <p><strong>Name:</strong> {scan.patientName}</p>
                <p><strong>ID:</strong> {scan.patientId}</p>
                <p><strong>Type:</strong> {scan.scanType}</p>
                <p><strong>Region:</strong> {scan.region}</p>
                <p><strong>Date:</strong>{" "}
                  {scan.uploadDate
                    ? new Date(scan.uploadDate).toLocaleString()
                    : "N/A"}
                </p>
              </div>
              <div className="flex gap-3 mt-3">
                <a
                  href={scan.imageUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex-1 text-center bg-indigo-600 text-white py-2 rounded-lg hover:bg-blue-700 transition"
                >
                  View Full Image
                </a>
                <button
                  onClick={() => downloadPDF(scan)}
                  className="flex-1 bg-green-500 text-white py-2 rounded-lg hover:bg-green-700 transition cursor-pointer"
                >
                  Download Report
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

export default DentistDashboard;
